# Plugins
plugins:
- jekyll-sitemap
- jekyll-twitter-plugin

safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SEBOL"
email: "admin@sebol.org"
description: "Sociedad de Economistas de Bolivia"
baseurl: ""
url: "https://www.sebol.org"
alias: "https://www.sebol.org"
# permalink: "/noticias/:title"
# googleAnalyticsTrackingId: "UA-100022870-1"
# googleAnalyticsSiteUrl: "www.bcde8.org"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Maps
# google_maps_javascript_api_key: AIzaSyDy_DAYgfh_AdZJLISWA_RhR518I40DACQ

# Organizer Info
organizerName: "SEBOL"
organizerAlternateName: "Sociedad de Economistas de Bolivia"
organizerDescription: ""
organizerEmail: "admin@sebol.org"
organizerLogo: "/img/seo/logo-upb-small.png"
organizerLink: "http://www.sebol.org"

# Head
metaKeywords: "event, bcde, sebol, upb, cochabamba, bolivia"
twitterAccount: "@SEBOLBolivia"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/nosotros/", text: "Nosotros"}
 - {permalink: "/conferencias/", text: "Conferencias"}
 - {permalink: "/erw/", text: "Talleres"}
 - {permalink: "/noticias/", text: "Noticias"}
 - {permalink: "/bcde9/", text: "BCDE9"}
 - {permalink: "/contact/", text: "Contacto"}
 # - {permalink: "/speakers/", text: "Directorio"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/buses.pdf", text: "Buses"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/blog/call-for-papers", text: "Call for papers"}
 # - {link: "http://www.sebol.org.bo", text: "About SEBOL"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 # - {permalink: "/team/", text: "Organizers"}
 # - {permalink: "/sponsors/", text: "Sponsors"}
rightNavigationButtons:
  - {link: "/bcde9/callforpapers", text: "Call For Papers"}
BCDEnavigationLinks:
 - {permalink: "/bcde9/", text: "Home"}
 - {permalink: "/bcde9/callforpapers", text: "Call for papers"}
 - {permalink: "/", text: "Sebol"}

# Hero Block
heroImage: "hero_sebol3.jpg"
# heroTitle: "SEBOL  <typeout>"
# eventDate: "Sociedad de Economistas de Bolivia"
# typeoutTextValues: '"", "Cochabamba-Bolivia", ""'
# typeoutFallback: "Universidad Privada Boliviana"
# heroButtons:
#  - {link: "/blog/registration", text: "Register Now"}
# - {permalink: "/#tickets", text: "Registration"}

# About Block
aboutTitle: "Nuestras actividades"
aboutBlock:
 - {title: "BCDE", image: "bcde7.jpg", text: 'La Conferencia Boliviana en Desarrollo Economico (BCDE) es la conferencia anual organizada por la SEBOL, INESAD y ABCE junto con el apoyo de las mejores universidades de Bolivia. <a href="/conferencias/">Detalles.</a>' }
 - {title: "ERW", image: "erw.jpg", text: 'El Taller de Investigación Económica (ERW) es el seminario mensual organizado por SEBOL, UPB, INESAD y ABCE, en el que se presentan trabajos de investigación académica en económia. <a href="/erw/">Detalles.</a>' }
 # - {title: "News Letter", image: "speakers.jpg", text: "Learn and discuss from a large array of topics and presenters from top universities and international organizations." }

# About BCDE
aboutBCDETitle: "Welcome to BCDE9"
aboutBCDEBlock:
 - {title: "Call for Papers", image: "callforpapers.jpg", text: 'Read our call for papers for the 9th Bolivian Conference on Development Economics. <a href="/bcde9/callforpapers/">Link.</a>' }
 # - {title: "Convocatoria Documentos de Trabajo", image: "erw.jpg", text: 'Lee la convocatoria para documentos de investigación. <a href="/erw/">Detalles.</a>' }
 # - {title: "News Letter", image: "speakers.jpg", text: "Learn and discuss from a large array of topics and presenters from top universities and international organizations." }


# Statistic Block
# statisticBlockImage: "hero_abstract_4.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere: students, professionals, policy makers"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of academic and policy discussion"}
 - {count: "50", specialCharacter: "+", info: "researchers", detail: "from local and international universities and international organizations"}
 - {count: "10", specialCharacter: "+", info: "parallel sessions", detail: "with presentations and full interaction with participants"}

# Latest News Block
latestNewsTitle: "Noticias recientes"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "Keynote speaker"
rockstarSpeakersSubTitle: "Special Guests"
rockstarSpeakersButtonText: "Learn more about our speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "UPB Cochabamba Campus"
eventLocationLink: "http://www.upb.edu/en/"
eventStreetAddress: "Av Juan Pablo II"
eventAddressLocality: "Cochabamba"
eventAddressLocalityRegion: "Cochabamba"
eventPostalCode: "79000"
eventAddressCountry: "Bolivia"
eventStartTime: "2017-10-26T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-10-28T20:00"
eventPlaceCoordinates: "-17.396416, -66.218217"
mapCenterCoordinates: "-17.396416, -66.218217"
mapMobileCenterCoordinates: "-17.396416, -66.218217"

# Venue Block
# venueBlockTitle: "Conference Venue"
# venueFeatures:
#  - {title: "UPB Campus Cochabamba", image: "venue_1.jpg", text: "Av. Victor Ustariz Km 6.5, Cochabamba-Bolivia <br> Phone number: (+591-4) 426-8287."}
venueBlockTitle: "Location </br> Universidad Privada de Santa Cruz"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Campus Universitario"
venueFeatures: ["Av. Paraguá y 4to. Anillo", "Tel.: +591 (3) 346 4000", '<a href="https://goo.gl/maps/yP9frJKCD3F2">Google Maps Directions</a>']



# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "@SEBOLBolivia"
twitterHashTag: "BCDE8"
# twitterFeed: "http://www.bcde8.org/tweetledee/favoritesjson.php"

# twitterFeed: "http://www.bcde8.org/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Suscríbete a nuestro boletín"
subscribeAction: "https://mc.us15.list-manage.com/subscribe/post?u=32ecc95787a5980a33901b562&amp;id=cc247ac02b"
# subscribeInfo: "Registration will be open around end of August. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=SEBOLBolivia", icon: "twitter"}
 - {link: "https://www.facebook.com/Sociedad-de-Economistas-de-Bolivia-379788332035459/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.sebol.org", text: "SEBOL"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:admin@sebol.org", text: "admin@sebol.org"}
 # -
 #  title: "FAQ"
 #  links:
 #   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Ultimas noticias"
blogCommentsEnabled: false

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About SEBOL"
aboutUs: "La Sociedad de Economistas de Bolivia (SEBOL) es una sociedad científica sin fines de lucro, legalmente establecida en el Estado Plurinacional de Bolivia. Tiene como actividad principal el fomento de los estudios e investigaciones, tanto de carácter teórico como empírico, que conduzcan al progreso, difusión y divulgación de la ciencia económica, así como cualquier otra iniciativa tendiente al máximo aprovechamiento de la ciencia económica en beneficio de la colectividad."
aboutUsRows:
 - {details: "Promover y publicar investigación científica en economía. En particular, trabajos que generen lecciones aplicables a la economía boliviana."}
 - {details: "Promover el libre intercambio de ideas en todas las áreas de la ciencia económica. (La SEBOL no tomará posturas políticas ni forzará a sus miembros a seguir líneas especificas de pensamiento económico.)"}

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-17.396416, -66.218217"
logisticsMapMobileCenterCoordinates: "-17.396416, -66.218217"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "view_cbb_5.jpg"
directionDetailsTitle: "Get around Cochabamba"
directionDetailsCards:
 - {title: "Airport", information: 'Jorge Wilstermann International Airport is conveniently located 6 Km. away from downtown Cochabamba. To-From airport information is available at <a href="http://www.sabsa.aero/aeropuerto-jorge-wilsterman/">airport website</a>.', title: "Airport"}
 - {title: "Conference Buses", information: 'Special buses taking participants to the conferences are available. Check here for <a href="/buses.pdf">bus routes</a>'}
 # - {title: "Hotels", information: 'BCDE has arranged preferential rates with the following hotels: <br><a href="http://granhotelcochabamba.com.bo">Gran Hotel Cochabamba</a> <br> (&#9733 &#9733 &#9733 &#9733 &#9733), 45 USD/night breakfast buffet included. <br> <a href="http://www.hotelreginabolivia.com">Hotel Regina (Prado)</a> <br>(&#9733 &#9733 &#9733 &#9733), 35 USD/night breakfast buffet included. <br> <br> For both hotels the reservation code is 8BCDE'}
 - {title: "Hotels", information: 'BCDE recommends the following hotels: <br><br><a href="http://www.tolomahotel.com.com.bo">Hotel Toloma</a> <br> (&#9733 &#9733 &#9733 &#9733). <br><a href="http://www.hotelreginabolivia.com">Hotel Regina (Prado)</a> <br>(&#9733 &#9733 &#9733 &#9733) <br><a href="http://www.hotelreginabolivia.com">'}
directionDetailsWideCards:
 -
  title: "Things to do while in Cochabamba"
  subCards:
   -
    title: "One day tours"
    links:
     - {permalink: "/tours/", text: "Ruinas de Incallajta"}
     - {permalink: "/tours/", text: "Incachaca"}
   -
    title: "Recommended"
    links:
     - {link: "https://www.lonelyplanet.com/bolivia/cochabamba/restaurants/a/poi-eat/1316004", text: "Restaurants"}
     - {link: "https://www.tripadvisor.com/Attractions-g297315-Activities-Cochabamba_Cochabamba_Department.html", text: "Things to do"}
   -
    title: "Venue Details"
    links:
     - {link: "http://www.upb.edu/en/", text: "UPB Facilities"}
     - {link: "/assets/UPBCampusMap.jpg", text: "UPB Campus Map"}

# Hackathon
hackathonTitle: "Pre-conference Workshops"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Conferencias Pasadas"
hackathonRows:
 - {title: "8va BCDE", image: "bcde2017.png", details: 'Realizada en la UPB. Cochabamba, 26 y 27 de octubre de 2017.<a href="http://www.bcde8.org" target="_blank"> Link.</a>'}
 - {title: "7ma BCDE", image: "bcde2016.png", details: 'Realizada en la UPB. La Paz, 8 y 9 de diciembre de 2016.<a href="http://www.inesad.edu.bo/web/en/bcde2016/" target="_blank"> Link.</a>'}
 - {title: "LACEA XX", image: "lacea.png", details: 'Realizada en la UPSA. Santa Cruz, 15 - 17 de octubre de 2015.<a href="http://laceameeting.com" target="_blank"> Link.</a>'}
 - {title: "6ta BCDE", image: "bcde2014.png", details: 'Realizada en la UPB. Cochabamba, 28 y 29 de agosto de 2014.<a href="http://www.inesad.edu.bo/bcde2014/" target="_blank"> Link.</a>'}
 - {title: "5ta BCDE", image: "bcde2013.png", details: 'Realizada en la UPSA. Santa Cruz, 14 y 15 de noviembre de 2013.<a href="http://www.inesad.edu.bo/bcde2013/" target="_blank"> Link.</a>'}
 - {title: "4ta BCDE", image: "bcde2012.png", details: 'Realizada en la EMI. La Paz, 6 y 7 de noviembre de 2012.<a href="http://www.inesad.edu.bo/bcde2012/" target="_blank"> Link.</a>'}
 - {title: "3ra BCDE", image: "bcde2011.png", details: 'Realizada en la UCB. La Paz, 14 y 15 de noviembre de 2011.<a href="http://www.inesad.edu.bo/bcde2011/" target="_blank"> Link.</a>'}
 - {title: "2da BCDE", image: "bcde2010.png", details: 'Realizada en la UPB, La Paz, 18 y 19 de noviembre de 2010.<a href="http://www.inesad.edu.bo/bcde2010/" target="_blank"> Link.</a>'}
 - {title: "1ra BCDE", image: "bcde2009.png", details: 'Realizada en la UPB, La Paz, 8 y 9 de octubre de 2009.<a href="http://www.inesad.edu.bo/web/en/bcde2009/" target="_blank"> Link.</a>'}
 # - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Expositores"

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "UPB Cochabamba Campus"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "Av Juan Pablo II"
hackathonAddressLocality: "Cochabamba"
hackathonAddressLocalityRegion: "Cochabamba"
hackathonPostalCode: "00000"
hackathonAddressCountry: "Bolivia"
hackathonTimeTitle: "BCDE Workshops 2017"
hackathonStartTime: "2017-10-25T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "-17.396416, -66.218217"
hackathonMapCenterCoordinates: "-17.396416, -66.218217"
hackathonMapMobileCenterCoordinates: "-17.396416, -66.218217"
